### ISSUE TITLE
Should be a seprate subx.js(without the monitor.js imported)

### ISSUE THREAD

**Issue by zxdong262** [tylerlong/subx#1]
Could be more modular this way.

**Comment by tylerlong** [comment]
I restructured the project this afternoon. I merged `computed.js` into `monitor.js` so that there are two and only two files in total.

One of SubX's core features is computed properties (getters). This feature is impossible without the code from `monitor.js` file.

For you suggestion I am still thinking about it. I want to make it simple to use.

If I separate them, user has to 

```js
import SubX from 'subx'
import { autoRun } from 'subx/src/monitor'
```

instead of

```js
import SubX from 'subx'
```

Current behavior is similar to MobX:  `mobx.autorun`.

Feel free to elaborate your idea. Thanks

**Comment by zxdong262** [comment]
Oh, I missed this line `import { runAndMonitor } from './monitor'`, I thought it was seprated, It is not.
